services:
  db:
    image: postgres:15-alpine
    container_name: logitrack-db
    restart: always
    environment:
      POSTGRES_USER: logitrack_user
      POSTGRES_PASSWORD: logitrack_pass
      POSTGRES_DB: logitrack_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d